
#define QUCS_NAME "@QUCS_NAME@"

#define PACKAGE_VERSION "@PROJECT_VERSION@"
#define PACKAGE_STRING "qucs @PROJECT_VERSION@"

#define HAVE_QTABWIDGET_SETMOVABLE "@HAVE_QTABWIDGET_SETMOVABLE@"
#define WITH_SPICE "@WITH_SPICE@"

#define GIT "@GIT@"

#define WASM_BUILD "@WASM_BUILD"

/* Simulator backend configuration */
#define NGSPICE_SHARED @NGSPICE_SHARED@

/* External process support categories */
#define EXTERNAL_SIMULATORS @EXTERNAL_SIMULATORS@
#define EXTERNAL_DATA_TOOLS @EXTERNAL_DATA_TOOLS@
#define EXTERNAL_POSTPROCESSING @EXTERNAL_POSTPROCESSING@
#define EXTERNAL_DESIGN_TOOLS @EXTERNAL_DESIGN_TOOLS@
#define EXTERNAL_BUILD_TOOLS @EXTERNAL_BUILD_TOOLS@
#define EXTERNAL_EDITORS @EXTERNAL_EDITORS@
